DPSG:
  CampGround:
    FacebookIntegration:
      PageId: null
      PageName: null
      AccessToken: null
    GoogleAnalytics:
      TrackingId: null

Neos:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 1

    Ui:
      frontendConfiguration:
        defaultInlineEditor: 'ckeditor5'

  Form:
    yamlPersistenceManager:
      savePath: 'resource://DPSG.CampGround/Private/Form/'

  ContentRepository:
    Search:
      indexAllWorkspaces: false

