
DPSG:
  CampGround:
    FacebookIntegration:
      PageId: null
      PageName: null
      AccessToken: null
    GoogleAnalytics:
      TrackingId: null
Neos:
  Form:
    yamlPersistenceManager:
      savePath: 'resource://DPSG.CampGround/Private/Form/'
